<?php

/** @var Bluethinkinc\ProductAvailability\ViewModel\ProductData $viewModal */
$viewModal = $block->getData('viewModel');
$moduleEnabled = $viewModal->moduleStatus();
$messagePLP = $viewModal->configMessagePLP();

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$availabilityOfProduct = $product->getData('product_availability');
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
        title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
        class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
    <div>
    <?php if ($moduleEnabled && $availabilityOfProduct !== null): ?>
        <?php $availabilityOfProduct = date("d-M-Y", strtotime($availabilityOfProduct)); ?>
<div>
    <span>
        <strong>
            <i>
                <?=
                    $block->escapeHtmlAttr($messagePLP).$block->escapeHtmlAttr($availabilityOfProduct)
                ?>
            </i>
        </strong>
    </span>
</div>

<?php endif; ?>
</strong>
